fragment EditCampaignData on Campaign {
  id
  title
  description
  dueBy
  isStarted
  isApproved
  isArchived
  isTemplate
  hasSentMessages
  contactsCount
  datawarehouseAvailable
  customFields
  logoImageUrl
  introHtml
  primaryColor
  textingHoursStart
  textingHoursEnd
  isAssignmentLimitedToTeams
  isAutoassignEnabled
  timezone
  teams {
    id
    title
  }
  messagingServiceSid
  editors
  readiness {
    basics
    textingHours
    integration
    contacts
    autoassign
    cannedResponses
    campaignGroups
    interactions
    texters
  }
  contactsFilename
}

query GetEditCampaignData($campaignId: String!) {
  campaign(id: $campaignId) {
    ...EditCampaignData
  }
}

query GetOrganizationDataForCampaignEdit($organizationId: String!) {
  organization(id: $organizationId) {
    id
    name
    uuid
    teams {
      id
      title
    }
    texters: people {
      id
      firstName
      lastName
      displayName
    }
    numbersApiKey
    messagingServices(active: true) {
      edges {
        node {
          name
        }
      }
    }
    campaigns(cursor: { offset: 0, limit: 5000 }) {
      campaigns {
        id
        title
        createdAt
      }
    }
  }
}

query GetCampaignEditJobs($campaignId: String!) {
  campaign(id: $campaignId) {
    id
    pendingJobs {
      id
      jobType
      assigned
      status
      resultMessage
    }
  }
}

mutation deleteJob($campaignId: String!, $id: String!) {
  deleteJob(campaignId: $campaignId, id: $id) {
    id
  }
}

mutation editCampaign($campaignId: String!, $campaign: CampaignInput!) {
  editCampaign(id: $campaignId, campaign: $campaign) {
    ...EditCampaignData
  }
}
